var group__om____operation____ =
[
    [ "->expression", "group__om____operation____expression__front__push__operation____.html", null ],
    [ "->lexicon", "group__om____operation____lexicon__front__push__operation____.html", null ],
    [ "->literal", "group__om____operation____literal__front__push__operation____.html", null ],
    [ "->operator", "group__om____operation____operator__front__push__operation____.html", null ],
    [ "<-characters", "group__om____operation____front__pull__character__operation____.html", null ],
    [ "<-code` points", "group__om____operation____front__pull__code__point__operation____.html", null ],
    [ "<-elements", "group__om____operation____front__pull__element__operation____.html", null ],
    [ "<-forms", "group__om____operation____front__pull__form__operation____.html", null ],
    [ "<-pairs", "group__om____operation____front__pull__pair__operation____.html", null ],
    [ "<-terms", "group__om____operation____front__pull__term__operation____.html", null ],
    [ "=", "group__om____operation____equals__operation____.html", null ],
    [ "characters->", "group__om____operation____back__pull__character__operation____.html", null ],
    [ "choose", "group__om____operation____choose__operation____.html", null ],
    [ "code` points->", "group__om____operation____back__pull__code__point__operation____.html", null ],
    [ "copy", "group__om____operation____copy__operation____.html", null ],
    [ "decode", "group__om____operation____decode__operation____.html", null ],
    [ "define", "group__om____operation____define__operation____.html", null ],
    [ "dequote", "group__om____operation____dequote__operation____.html", null ],
    [ "do", "group__om____operation____do__operation____.html", null ],
    [ "drop", "group__om____operation____drop__operation____.html", null ],
    [ "elements->", "group__om____operation____back__pull__element__operation____.html", null ],
    [ "elements->operand", "group__om____operation____back__pull__operand__operation____.html", null ],
    [ "elements->operator", "group__om____operation____back__pull__operator__operation____.html", null ],
    [ "elements->separator", "group__om____operation____back__pull__separator__operation____.html", null ],
    [ "encode", "group__om____operation____encode__operation____.html", null ],
    [ "environment", "group__om____operation____environment__operation____.html", null ],
    [ "evaluate", "group__om____operation____evaluate__operation____.html", null ],
    [ "expression", "group__om____operation____expression__operation____.html", null ],
    [ "expression<-", "group__om____operation____expression__back__push__operation____.html", null ],
    [ "fill", "group__om____operation____fill__operation____.html", null ],
    [ "find", "group__om____operation____find__operation____.html", null ],
    [ "forms->", "group__om____operation____back__pull__form__operation____.html", null ],
    [ "inject", "group__om____operation____inject__operation____.html", null ],
    [ "lexicon", "group__om____operation____lexicon__operation____.html", null ],
    [ "lexicon<-", "group__om____operation____lexicon__back__push__operation____.html", null ],
    [ "literal<-", "group__om____operation____literal__back__push__operation____.html", null ],
    [ "normalize", "group__om____operation____normalize__operation____.html", null ],
    [ "operand", "group__om____operation____operand__operation____.html", null ],
    [ "operand<-elements", "group__om____operation____front__pull__operand__operation____.html", null ],
    [ "operator", "group__om____operation____operator__operation____.html", null ],
    [ "operator<-", "group__om____operation____operator__back__push__operation____.html", null ],
    [ "operator<-elements", "group__om____operation____front__pull__operator__operation____.html", null ],
    [ "pair", "group__om____operation____pair__operation____.html", null ],
    [ "pairs->", "group__om____operation____back__pull__pair__operation____.html", null ],
    [ "quote", "group__om____operation____quote__operation____.html", null ],
    [ "rearrange", "group__om____operation____rearrange__operation____.html", null ],
    [ "separator", "group__om____operation____separator__operation____.html", null ],
    [ "separator<-elements", "group__om____operation____front__pull__separator__operation____.html", null ],
    [ "skip", "group__om____operation____skip__operation____.html", null ],
    [ "substitute", "group__om____operation____substitute__operation____.html", null ],
    [ "swap", "group__om____operation____swap__operation____.html", null ],
    [ "system", "group__om____operation____system__operation____.html", null ],
    [ "terms->", "group__om____operation____back__pull__term__operation____.html", null ]
];