var group__om____operations____ =
[
    [ "->expression", "group__om____operations____expression__front__push__operation____.html", null ],
    [ "->lexicon", "group__om____operations____lexicon__front__push__operation____.html", null ],
    [ "->literal", "group__om____operations____literal__front__push__operation____.html", null ],
    [ "->operator", "group__om____operations____operator__front__push__operation____.html", null ],
    [ "<-characters", "group__om____operations____front__pull__character__operation____.html", null ],
    [ "<-code` points", "group__om____operations____front__pull__code__point__operation____.html", null ],
    [ "<-elements", "group__om____operations____front__pull__element__operation____.html", null ],
    [ "<-forms", "group__om____operations____front__pull__form__operation____.html", null ],
    [ "<-pairs", "group__om____operations____front__pull__pair__operation____.html", null ],
    [ "<-terms", "group__om____operations____front__pull__term__operation____.html", null ],
    [ "=", "group__om____operations____equals__operation____.html", null ],
    [ "characters->", "group__om____operations____back__pull__character__operation____.html", null ],
    [ "choose", "group__om____operations____choose__operation____.html", null ],
    [ "code` points->", "group__om____operations____back__pull__code__point__operation____.html", null ],
    [ "copy", "group__om____operations____copy__operation____.html", null ],
    [ "decode", "group__om____operations____decode__operation____.html", null ],
    [ "define", "group__om____operations____define__operation____.html", null ],
    [ "dequote", "group__om____operations____dequote__operation____.html", null ],
    [ "do", "group__om____operations____do__operation____.html", null ],
    [ "drop", "group__om____operations____drop__operation____.html", null ],
    [ "elements->", "group__om____operations____back__pull__element__operation____.html", null ],
    [ "elements->operand", "group__om____operations____back__pull__operand__operation____.html", null ],
    [ "elements->operator", "group__om____operations____back__pull__operator__operation____.html", null ],
    [ "elements->separator", "group__om____operations____back__pull__separator__operation____.html", null ],
    [ "encode", "group__om____operations____encode__operation____.html", null ],
    [ "environment", "group__om____operations____environment__operation____.html", null ],
    [ "evaluate", "group__om____operations____evaluate__operation____.html", null ],
    [ "expression", "group__om____operations____expression__operation____.html", null ],
    [ "expression<-", "group__om____operations____expression__back__push__operation____.html", null ],
    [ "fill", "group__om____operations____fill__operation____.html", null ],
    [ "find", "group__om____operations____find__operation____.html", null ],
    [ "forms->", "group__om____operations____back__pull__form__operation____.html", null ],
    [ "inject", "group__om____operations____inject__operation____.html", null ],
    [ "lexicon", "group__om____operations____lexicon__operation____.html", null ],
    [ "lexicon<-", "group__om____operations____lexicon__back__push__operation____.html", null ],
    [ "literal<-", "group__om____operations____literal__back__push__operation____.html", null ],
    [ "normalize", "group__om____operations____normalize__operation____.html", null ],
    [ "operand", "group__om____operations____operand__operation____.html", null ],
    [ "operand<-elements", "group__om____operations____front__pull__operand__operation____.html", null ],
    [ "operator", "group__om____operations____operator__operation____.html", null ],
    [ "operator<-", "group__om____operations____operator__back__push__operation____.html", null ],
    [ "operator<-elements", "group__om____operations____front__pull__operator__operation____.html", null ],
    [ "pairs->", "group__om____operations____back__pull__pair__operation____.html", null ],
    [ "quote", "group__om____operations____quote__operation____.html", null ],
    [ "rearrange", "group__om____operations____rearrange__operation____.html", null ],
    [ "separator", "group__om____operations____separator__operation____.html", null ],
    [ "separator<-elements", "group__om____operations____front__pull__separator__operation____.html", null ],
    [ "skip", "group__om____operations____skip__operation____.html", null ],
    [ "substitute", "group__om____operations____substitute__operation____.html", null ],
    [ "swap", "group__om____operations____swap__operation____.html", null ],
    [ "system", "group__om____operations____system__operation____.html", null ],
    [ "terms->", "group__om____operations____back__pull__term__operation____.html", null ]
];