var group__operations =
[
    [ "->expression", "group__expression__front__push__operation.html", null ],
    [ "->lexicon", "group__lexicon__front__push__operation.html", null ],
    [ "->literal", "group__literal__front__push__operation.html", null ],
    [ "->operator", "group__operator__front__push__operation.html", null ],
    [ "<-characters", "group__front__pull__character__operation.html", null ],
    [ "<-code` points", "group__front__pull__code__point__operation.html", null ],
    [ "<-elements", "group__front__pull__element__operation.html", null ],
    [ "<-forms", "group__front__pull__form__operation.html", null ],
    [ "<-pairs", "group__front__pull__pair__operation.html", null ],
    [ "<-terms", "group__front__pull__term__operation.html", null ],
    [ "=", "group__equals__operation.html", null ],
    [ "characters->", "group__back__pull__character__operation.html", null ],
    [ "choose", "group__choose__operation.html", null ],
    [ "code` points->", "group__back__pull__code__point__operation.html", null ],
    [ "copy", "group__copy__operation.html", null ],
    [ "decode", "group__decode__operation.html", null ],
    [ "define", "group__define__operation.html", null ],
    [ "dequote", "group__dequote__operation.html", null ],
    [ "do", "group__do__operation.html", null ],
    [ "drop", "group__drop__operation.html", null ],
    [ "elements->", "group__back__pull__element__operation.html", null ],
    [ "elements->operand", "group__back__pull__operand__operation.html", null ],
    [ "elements->operator", "group__back__pull__operator__operation.html", null ],
    [ "elements->separator", "group__back__pull__separator__operation.html", null ],
    [ "encode", "group__encode__operation.html", null ],
    [ "environment", "group__environment__operation.html", null ],
    [ "evaluate", "group__evaluate__operation.html", null ],
    [ "expression", "group__expression__operation.html", null ],
    [ "expression<-", "group__expression__back__push__operation.html", null ],
    [ "fill", "group__fill__operation.html", null ],
    [ "find", "group__find__operation.html", null ],
    [ "forms->", "group__back__pull__form__operation.html", null ],
    [ "inject", "group__inject__operation.html", null ],
    [ "lexicon", "group__lexicon__operation.html", null ],
    [ "lexicon<-", "group__lexicon__back__push__operation.html", null ],
    [ "literal<-", "group__literal__back__push__operation.html", null ],
    [ "normalize", "group__normalize__operation.html", null ],
    [ "operand", "group__operand__operation.html", null ],
    [ "operand<-elements", "group__front__pull__operand__operation.html", null ],
    [ "operator", "group__operator__operation.html", null ],
    [ "operator<-", "group__operator__back__push__operation.html", null ],
    [ "operator<-elements", "group__front__pull__operator__operation.html", null ],
    [ "pairs->", "group__back__pull__pair__operation.html", null ],
    [ "quote", "group__quote__operation.html", null ],
    [ "rearrange", "group__rearrange__operation.html", null ],
    [ "separator", "group__separator__operation.html", null ],
    [ "separator<-elements", "group__front__pull__separator__operation.html", null ],
    [ "skip", "group__skip__operation.html", null ],
    [ "substitute", "group__substitute__operation.html", null ],
    [ "swap", "group__swap__operation.html", null ],
    [ "system", "group__system__operation.html", null ],
    [ "terms->", "group__back__pull__term__operation.html", null ]
];