Om: code/om.cpp File Reference
om.cpp File Reference
Om source file.
#include "om.hpp"
#include "om/sinks/stream_sink.hpp"
#include "om/sources/stream_source.hpp"
#include "om/system.hpp"
Functions
int main (int const theArgumentCount, char const *const theArgumentArray[])
Detailed Description
Version
0.1.2
Date
2012-2013
Copyright
Copyright (c) Sparist. All rights reserved. This program and the accompanying materials are made available under the terms of the Eclipse Public License, Version 1.0, which accompanies this distribution.
Authors
Jason Erb - Initial API, implementation, and documentation.
Definition in file om.cpp.
Function Documentation
int main (int const theArgumentCount, char const *const theArgumentArray[])
Parameters
theArgumentCount The argument count; must be greater than 0.
theArgumentArray The argument array contains (in order):
The program invocation.
(Optional) A valid UTF-8 locale string compatible with boost::locale.
Definition at line 32 of file om.cpp.
References Om::Translator::Evaluate(), Om::System::Get(), and Om::System::Initialize().
 {
     assert( 0 < theArgumentCount );
     assert( theArgumentArray );
     Om::System::Get().Initialize(
         ( 1 < theArgumentCount )?
         theArgumentArray[ 1 ]:
         "en_US.UTF-8"
     );
 #if defined( Om_Macros_Test_ )
     int const theResult = UnitTest::RunAllTests();
 #endif
     typedef Om::Sources::StreamSource<> CodeUnitSource;
     CodeUnitSource theCodeUnitSource( std::cin );
     Om::Sources::CodePointSource< CodeUnitSource > theCodePointSource(
         theCodeUnitSource,
         CodeUnitSource()
     );
     typedef Om::Sinks::StreamSink<> CodeUnitSink;
     CodeUnitSink theCodeUnitSink( std::cout );
     Om::Sinks::CodePointSink< CodeUnitSink > theCodePointSink( theCodeUnitSink );
     Om::System::Get().Evaluate(
         theCodePointSource,
         theCodePointSink
     );
 #if defined( Om_Macros_Test_ )
     return( theResult );
 #else
     return( EXIT_SUCCESS );
 #endif
 }