var searchData=
[
  ['decode',['Decode',['../struct_om_1_1_operator.html#ac9aa0a32ff10989dc60f4c3c592ccd04',1,'Om::Operator']]],
  ['decode',['decode',['../group__decode__operation.html',1,'']]],
  ['decode_5foperation_2ecpp',['decode_operation.cpp',['../decode__operation_8cpp.html',1,'']]],
  ['decode_5foperation_2ehpp',['decode_operation.hpp',['../decode__operation_8hpp.html',1,'']]],
  ['decodeoperation',['DecodeOperation',['../struct_om_1_1_operations_1_1_decode_operation.html',1,'Om::Operations']]],
  ['decrementownercount',['DecrementOwnerCount',['../struct_om_1_1_shareable.html#a8aff10a3dcd2829a50fcccb271c21e57',1,'Om::Shareable']]],
  ['default_5fatom_2ecpp',['default_atom.cpp',['../default__atom_8cpp.html',1,'']]],
  ['default_5fatom_2ehpp',['default_atom.hpp',['../default__atom_8hpp.html',1,'']]],
  ['default_5fcopyable_2ecpp',['default_copyable.cpp',['../default__copyable_8cpp.html',1,'']]],
  ['default_5fcopyable_2ehpp',['default_copyable.hpp',['../default__copyable_8hpp.html',1,'']]],
  ['default_5felement_2ecpp',['default_element.cpp',['../default__element_8cpp.html',1,'']]],
  ['default_5felement_2ehpp',['default_element.hpp',['../default__element_8hpp.html',1,'']]],
  ['default_5fgiveable_2ecpp',['default_giveable.cpp',['../default__giveable_8cpp.html',1,'']]],
  ['default_5fgiveable_2ehpp',['default_giveable.hpp',['../default__giveable_8hpp.html',1,'']]],
  ['default_5fmoveable_2ecpp',['default_moveable.cpp',['../default__moveable_8cpp.html',1,'']]],
  ['default_5fmoveable_2ehpp',['default_moveable.hpp',['../default__moveable_8hpp.html',1,'']]],
  ['default_5foperation_2ecpp',['default_operation.cpp',['../default__operation_8cpp.html',1,'']]],
  ['default_5foperation_2ehpp',['default_operation.hpp',['../default__operation_8hpp.html',1,'']]],
  ['default_5fprogram_2ecpp',['default_program.cpp',['../default__program_8cpp.html',1,'']]],
  ['default_5fprogram_2ehpp',['default_program.hpp',['../default__program_8hpp.html',1,'']]],
  ['default_5fqueue_2ecpp',['default_queue.cpp',['../default__queue_8cpp.html',1,'']]],
  ['default_5fqueue_2ehpp',['default_queue.hpp',['../default__queue_8hpp.html',1,'']]],
  ['default_5fsink_2ecpp',['default_sink.cpp',['../default__sink_8cpp.html',1,'']]],
  ['default_5fsink_2ehpp',['default_sink.hpp',['../default__sink_8hpp.html',1,'']]],
  ['default_5fsource_2ecpp',['default_source.cpp',['../default__source_8cpp.html',1,'']]],
  ['default_5fsource_2ehpp',['default_source.hpp',['../default__source_8hpp.html',1,'']]],
  ['defaultatom',['DefaultAtom',['../struct_om_1_1_default_atom.html#a5d47432883ae12447183b44a5879966e',1,'Om::DefaultAtom::DefaultAtom()'],['../struct_om_1_1_default_atom.html#a01a71de544c730f750e87f370ce0f8ce',1,'Om::DefaultAtom::DefaultAtom(char const theCodeUnitIterator[])'],['../struct_om_1_1_default_atom.html#aa0f09eed1143351b39f7900b596d4764',1,'Om::DefaultAtom::DefaultAtom(char const theCodeUnit)']]],
  ['defaultatom',['DefaultAtom',['../struct_om_1_1_default_atom.html',1,'Om']]],
  ['defaultatom_3c_20operator_20_3e',['DefaultAtom&lt; Operator &gt;',['../struct_om_1_1_default_atom.html',1,'Om']]],
  ['defaultatom_3c_20separator_20_3e',['DefaultAtom&lt; Separator &gt;',['../struct_om_1_1_default_atom.html',1,'Om']]],
  ['defaultcopyable',['DefaultCopyable',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20expression_2c_20program_20_3e',['DefaultCopyable&lt; Expression, Program &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20lexicon_2c_20program_20_3e',['DefaultCopyable&lt; Lexicon, Program &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20literal_2c_20program_20_3e',['DefaultCopyable&lt; Literal, Program &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20null_2c_20program_20_3e',['DefaultCopyable&lt; Null, Program &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20operand_2c_20element_20_3e',['DefaultCopyable&lt; Operand, Element &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20operator_2c_20atom_20_3e',['DefaultCopyable&lt; Operator, Atom &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20separator_2c_20atom_20_3e',['DefaultCopyable&lt; Separator, Atom &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultcopyable_3c_20thisimplementation_2c_20atom_20_3e',['DefaultCopyable&lt; ThisImplementation, Atom &gt;',['../struct_om_1_1_default_copyable.html',1,'Om']]],
  ['defaultelement',['DefaultElement',['../struct_om_1_1_default_element.html',1,'Om']]],
  ['defaultelement_3c_20operand_20_3e',['DefaultElement&lt; Operand &gt;',['../struct_om_1_1_default_element.html',1,'Om']]],
  ['defaultelement_3c_20operator_2c_20atom_20_3e',['DefaultElement&lt; Operator, Atom &gt;',['../struct_om_1_1_default_element.html',1,'Om']]],
  ['defaultelement_3c_20separator_2c_20atom_20_3e',['DefaultElement&lt; Separator, Atom &gt;',['../struct_om_1_1_default_element.html',1,'Om']]],
  ['defaultelement_3c_20thisimplementation_2c_20atom_20_3e',['DefaultElement&lt; ThisImplementation, Atom &gt;',['../struct_om_1_1_default_element.html',1,'Om']]],
  ['defaultgiveable',['DefaultGiveable',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20expression_2c_20program_20_3e',['DefaultGiveable&lt; Expression, Program &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20lexicon_2c_20program_20_3e',['DefaultGiveable&lt; Lexicon, Program &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20literal_2c_20program_20_3e',['DefaultGiveable&lt; Literal, Program &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20null_2c_20program_20_3e',['DefaultGiveable&lt; Null, Program &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20operand_2c_20element_20_3e',['DefaultGiveable&lt; Operand, Element &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20operator_2c_20atom_20_3e',['DefaultGiveable&lt; Operator, Atom &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20separator_2c_20atom_20_3e',['DefaultGiveable&lt; Separator, Atom &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultgiveable_3c_20thisimplementation_2c_20atom_20_3e',['DefaultGiveable&lt; ThisImplementation, Atom &gt;',['../struct_om_1_1_default_giveable.html',1,'Om']]],
  ['defaultmoveable',['DefaultMoveable',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20expression_2c_20defaultcopyable_3c_20expression_2c_20program_20_3e_20_3e',['DefaultMoveable&lt; Expression, DefaultCopyable&lt; Expression, Program &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20lexicon_2c_20defaultcopyable_3c_20lexicon_2c_20program_20_3e_20_3e',['DefaultMoveable&lt; Lexicon, DefaultCopyable&lt; Lexicon, Program &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20literal_2c_20defaultcopyable_3c_20literal_2c_20program_20_3e_20_3e',['DefaultMoveable&lt; Literal, DefaultCopyable&lt; Literal, Program &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20null_2c_20defaultcopyable_3c_20null_2c_20program_20_3e_20_3e',['DefaultMoveable&lt; Null, DefaultCopyable&lt; Null, Program &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20operand_2c_20defaultcopyable_3c_20operand_2c_20element_20_3e_20_3e',['DefaultMoveable&lt; Operand, DefaultCopyable&lt; Operand, Element &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20operator_2c_20defaultcopyable_3c_20operator_2c_20atom_20_3e_20_3e',['DefaultMoveable&lt; Operator, DefaultCopyable&lt; Operator, Atom &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20separator_2c_20defaultcopyable_3c_20separator_2c_20atom_20_3e_20_3e',['DefaultMoveable&lt; Separator, DefaultCopyable&lt; Separator, Atom &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20thisimplementation_2c_20defaultcopyable_3c_20thisimplementation_2c_20atom_20_3e_20_3e',['DefaultMoveable&lt; ThisImplementation, DefaultCopyable&lt; ThisImplementation, Atom &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultmoveable_3c_20thisimplementation_2c_20defaultcopyable_3c_20thisimplementation_2c_20thisinterface_20_3e_20_3e',['DefaultMoveable&lt; ThisImplementation, DefaultCopyable&lt; ThisImplementation, ThisInterface &gt; &gt;',['../struct_om_1_1_default_moveable.html',1,'Om']]],
  ['defaultoperation',['DefaultOperation',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20chooseoperation_20_3e',['DefaultOperation&lt; ChooseOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20copyoperation_20_3e',['DefaultOperation&lt; CopyOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20decodeoperation_20_3e',['DefaultOperation&lt; DecodeOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20defineoperation_20_3e',['DefaultOperation&lt; DefineOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20dequoteoperation_20_3e',['DefaultOperation&lt; DequoteOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20dropoperation_20_3e',['DefaultOperation&lt; DropOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20encodeoperation_20_3e',['DefaultOperation&lt; EncodeOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20equalsoperation_20_3e',['DefaultOperation&lt; EqualsOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20evaluateoperation_20_3e',['DefaultOperation&lt; EvaluateOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20filloperation_20_3e',['DefaultOperation&lt; FillOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20findoperation_20_3e',['DefaultOperation&lt; FindOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20frontpushoperation_3c_20thisprogram_2c_20thisimplementation_20_3e_20_3e',['DefaultOperation&lt; FrontPushOperation&lt; ThisProgram, ThisImplementation &gt; &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20injectoperation_20_3e',['DefaultOperation&lt; InjectOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20normalizeoperation_20_3e',['DefaultOperation&lt; NormalizeOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20programoperation_3c_20thisprogram_20_3e_20_3e',['DefaultOperation&lt; ProgramOperation&lt; ThisProgram &gt; &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20pulloperation_3c_20thisprogram_2c_20thisimplementation_20_3e_20_3e',['DefaultOperation&lt; PullOperation&lt; ThisProgram, ThisImplementation &gt; &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20quoteoperation_20_3e',['DefaultOperation&lt; QuoteOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20skipoperation_20_3e',['DefaultOperation&lt; SkipOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20substituteoperation_20_3e',['DefaultOperation&lt; SubstituteOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultoperation_3c_20swapoperation_20_3e',['DefaultOperation&lt; SwapOperation &gt;',['../struct_om_1_1_default_operation.html',1,'Om']]],
  ['defaultprogram',['DefaultProgram',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20expression_20_3e',['DefaultProgram&lt; Expression &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20lexicon_20_3e',['DefaultProgram&lt; Lexicon &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20literal_20_3e',['DefaultProgram&lt; Literal &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20null_20_3e',['DefaultProgram&lt; Null &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20operand_2c_20element_20_3e',['DefaultProgram&lt; Operand, Element &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20operator_2c_20atom_20_3e',['DefaultProgram&lt; Operator, Atom &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20separator_2c_20atom_20_3e',['DefaultProgram&lt; Separator, Atom &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultprogram_3c_20thisimplementation_2c_20atom_20_3e',['DefaultProgram&lt; ThisImplementation, Atom &gt;',['../struct_om_1_1_default_program.html',1,'Om']]],
  ['defaultqueue',['DefaultQueue',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20evaluator_20_3e',['DefaultQueue&lt; Evaluator &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20expression_2c_20defaultgiveable_3c_20expression_2c_20program_20_3e_20_3e',['DefaultQueue&lt; Expression, DefaultGiveable&lt; Expression, Program &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20lexicon_2c_20defaultgiveable_3c_20lexicon_2c_20program_20_3e_20_3e',['DefaultQueue&lt; Lexicon, DefaultGiveable&lt; Lexicon, Program &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20literal_2c_20defaultgiveable_3c_20literal_2c_20program_20_3e_20_3e',['DefaultQueue&lt; Literal, DefaultGiveable&lt; Literal, Program &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20null_2c_20defaultgiveable_3c_20null_2c_20program_20_3e_20_3e',['DefaultQueue&lt; Null, DefaultGiveable&lt; Null, Program &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20operand_2c_20defaultgiveable_3c_20operand_2c_20element_20_3e_20_3e',['DefaultQueue&lt; Operand, DefaultGiveable&lt; Operand, Element &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20operator_2c_20defaultgiveable_3c_20operator_2c_20atom_20_3e_20_3e',['DefaultQueue&lt; Operator, DefaultGiveable&lt; Operator, Atom &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20separator_2c_20defaultgiveable_3c_20separator_2c_20atom_20_3e_20_3e',['DefaultQueue&lt; Separator, DefaultGiveable&lt; Separator, Atom &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20thisimplementation_2c_20defaultgiveable_3c_20thisimplementation_2c_20atom_20_3e_20_3e',['DefaultQueue&lt; ThisImplementation, DefaultGiveable&lt; ThisImplementation, Atom &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20thisimplementation_2c_20defaultgiveable_3c_20thisimplementation_2c_20thisinterface_20_3e_20_3e',['DefaultQueue&lt; ThisImplementation, DefaultGiveable&lt; ThisImplementation, ThisInterface &gt; &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultqueue_3c_20writer_20_3e',['DefaultQueue&lt; Writer &gt;',['../struct_om_1_1_default_queue.html',1,'Om']]],
  ['defaultsink',['DefaultSink',['../struct_om_1_1_sinks_1_1_default_sink.html',1,'Om::Sinks']]],
  ['defaultsink_3c_20codepoint_20const_2c_20codepointsink_3c_20thiscodeunititerator_20_3e_20_3e',['DefaultSink&lt; CodePoint const, CodePointSink&lt; ThisCodeUnitIterator &gt; &gt;',['../struct_om_1_1_sinks_1_1_default_sink.html',1,'Om::Sinks']]],
  ['defaultsink_3c_20lexicon_20const_2c_20translator_20_3e',['DefaultSink&lt; Lexicon const, Translator &gt;',['../struct_om_1_1_sinks_1_1_default_sink.html',1,'Om::Sinks']]],
  ['defaultsink_3c_20thisitem_2c_20containerbacksink_3c_20thisitem_2c_20thiscontainer_20_3e_20_3e',['DefaultSink&lt; ThisItem, ContainerBackSink&lt; ThisItem, ThisContainer &gt; &gt;',['../struct_om_1_1_sinks_1_1_default_sink.html',1,'Om::Sinks']]],
  ['defaultsink_3c_20thisitem_2c_20containerfrontsink_3c_20thisitem_2c_20thiscontainer_20_3e_20_3e',['DefaultSink&lt; ThisItem, ContainerFrontSink&lt; ThisItem, ThisContainer &gt; &gt;',['../struct_om_1_1_sinks_1_1_default_sink.html',1,'Om::Sinks']]],
  ['defaultsink_3c_20thisitem_2c_20iteratorsink_3c_20thisitem_2c_20std_3a_3aostreambuf_5fiterator_3c_20thisitem_20_3e_20_3e_20_3e',['DefaultSink&lt; ThisItem, IteratorSink&lt; ThisItem, std::ostreambuf_iterator&lt; ThisItem &gt; &gt; &gt;',['../struct_om_1_1_sinks_1_1_default_sink.html',1,'Om::Sinks']]],
  ['defaultsink_3c_20thisitem_2c_20iteratorsink_3c_20thisitem_2c_20thisiterator_20_3e_20_3e',['DefaultSink&lt; ThisItem, IteratorSink&lt; ThisItem, ThisIterator &gt; &gt;',['../struct_om_1_1_sinks_1_1_default_sink.html',1,'Om::Sinks']]],
  ['defaultsource',['DefaultSource',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20char_20const_20_2c_20iteratorsource_3c_20char_20const_20_2c_20char_20const_20_2a_20_3e_20_3e',['DefaultSource&lt; char const , IteratorSource&lt; char const , char const * &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20codepoint_20const_2c_20codepointsource_3c_20iteratorsource_3c_20char_20const_2c_20char_20const_20_2a_20_3e_20_3e_20_3e',['DefaultSource&lt; CodePoint const, CodePointSource&lt; IteratorSource&lt; char const, char const * &gt; &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20codepoint_20const_2c_20codepointsource_3c_20thiscodeunititerator_20_3e_20_3e',['DefaultSource&lt; CodePoint const, CodePointSource&lt; ThisCodeUnitIterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20codepoint_20const_2c_20parser_20_3e',['DefaultSource&lt; CodePoint const, Parser &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20element_20const_20_2c_20iteratorpairsource_3c_20element_20const_20_2c_20elementdeque_3a_3aconst_5fiterator_20_3e_20_3e',['DefaultSource&lt; Element const , IteratorPairSource&lt; Element const , ElementDeque::const_iterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20element_20const_2c_20elementrange_20_3e',['DefaultSource&lt; Element const, ElementRange &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20element_2c_20iteratorpairsource_3c_20element_2c_20elementdeque_3a_3aiterator_20_3e_20_3e',['DefaultSource&lt; Element, IteratorPairSource&lt; Element, ElementDeque::iterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20form_20const_20_2c_20iteratorpairsource_3c_20form_20const_20_2c_20formdeque_3a_3aconst_5fiterator_20_3e_20_3e',['DefaultSource&lt; Form const , IteratorPairSource&lt; Form const , FormDeque::const_iterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20form_2c_20iteratorpairsource_3c_20form_2c_20formdeque_3a_3aiterator_20_3e_20_3e',['DefaultSource&lt; Form, IteratorPairSource&lt; Form, FormDeque::iterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20operand_20const_20_2c_20iteratorpairsource_3c_20operand_20const_20_2c_20operanddeque_3a_3aconst_5fiterator_20_3e_20_3e',['DefaultSource&lt; Operand const , IteratorPairSource&lt; Operand const , OperandDeque::const_iterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20operand_2c_20iteratorpairsource_3c_20operand_2c_20operanddeque_3a_3aiterator_20_3e_20_3e',['DefaultSource&lt; Operand, IteratorPairSource&lt; Operand, OperandDeque::iterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20std_3a_3astring_2c_20codepointstringbacksource_3c_20thisstringiterator_20_3e_20_3e',['DefaultSource&lt; std::string, CodePointStringBackSource&lt; ThisStringIterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20std_3a_3astring_2c_20codepointstringfrontsource_3c_20thisstringiterator_20_3e_20_3e',['DefaultSource&lt; std::string, CodePointStringFrontSource&lt; ThisStringIterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20thisitem_20const_2c_20streamsource_3c_20thisitem_20_3e_20_3e',['DefaultSource&lt; ThisItem const, StreamSource&lt; ThisItem &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20thisitem_2c_20containerbacksource_3c_20thisitem_2c_20thiscontainer_20_3e_20_3e',['DefaultSource&lt; ThisItem, ContainerBackSource&lt; ThisItem, ThisContainer &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20thisitem_2c_20containerfrontsource_3c_20thisitem_2c_20thiscontainer_20_3e_20_3e',['DefaultSource&lt; ThisItem, ContainerFrontSource&lt; ThisItem, ThisContainer &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20thisitem_2c_20emptysource_3c_20thisitem_20_3e_20_3e',['DefaultSource&lt; ThisItem, EmptySource&lt; ThisItem &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20thisitem_2c_20iteratorpairsource_3c_20thisitem_2c_20thisiterator_20_3e_20_3e',['DefaultSource&lt; ThisItem, IteratorPairSource&lt; ThisItem, ThisIterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20thisitem_2c_20iteratorsource_3c_20thisitem_2c_20thisiterator_20_3e_20_3e',['DefaultSource&lt; ThisItem, IteratorSource&lt; ThisItem, ThisIterator &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['defaultsource_3c_20thisitem_2c_20singletonsource_3c_20thisitem_20_3e_20_3e',['DefaultSource&lt; ThisItem, SingletonSource&lt; ThisItem &gt; &gt;',['../struct_om_1_1_sources_1_1_default_source.html',1,'Om::Sources']]],
  ['define',['define',['../group__define__operation.html',1,'']]],
  ['define_5foperation_2ecpp',['define_operation.cpp',['../define__operation_8cpp.html',1,'']]],
  ['define_5foperation_2ehpp',['define_operation.hpp',['../define__operation_8hpp.html',1,'']]],
  ['defineoperation',['DefineOperation',['../struct_om_1_1_operations_1_1_define_operation.html',1,'Om::Operations']]],
  ['defineoperation',['DefineOperation',['../struct_om_1_1_operations_1_1_define_operation.html#a195d1ce2171d13ffe80e191534e99952',1,'Om::Operations::DefineOperation']]],
  ['definition',['Definition',['../struct_om_1_1_system.html#a8e436edc1f0c18b450e7ac127f20b249',1,'Om::System::Definition()'],['../struct_om_1_1_definition.html#af12defeaf04a7eaddb8bdef505b82bb8',1,'Om::Definition::Definition()']]],
  ['definition',['Definition',['../struct_om_1_1_definition.html',1,'Om']]],
  ['definition_2ecpp',['definition.cpp',['../definition_8cpp.html',1,'']]],
  ['definition_2ehpp',['definition.hpp',['../definition_8hpp.html',1,'']]],
  ['dequote',['dequote',['../group__dequote__operation.html',1,'']]],
  ['dequote_5foperation_2ecpp',['dequote_operation.cpp',['../dequote__operation_8cpp.html',1,'']]],
  ['dequote_5foperation_2ehpp',['dequote_operation.hpp',['../dequote__operation_8hpp.html',1,'']]],
  ['dequoteoperation',['DequoteOperation',['../struct_om_1_1_operations_1_1_dequote_operation.html',1,'Om::Operations']]],
  ['do',['do',['../group__do__operation.html',1,'']]],
  ['do_5foperation_2ecpp',['do_operation.cpp',['../do__operation_8cpp.html',1,'']]],
  ['do_5foperation_2ehpp',['do_operation.hpp',['../do__operation_8hpp.html',1,'']]],
  ['dooperation',['DoOperation',['../struct_om_1_1_operations_1_1_do_operation.html',1,'Om::Operations']]],
  ['drop',['drop',['../group__drop__operation.html',1,'']]],
  ['drop_5foperation_2ecpp',['drop_operation.cpp',['../drop__operation_8cpp.html',1,'']]],
  ['drop_5foperation_2ehpp',['drop_operation.hpp',['../drop__operation_8hpp.html',1,'']]],
  ['dropoperation',['DropOperation',['../struct_om_1_1_operations_1_1_drop_operation.html',1,'Om::Operations']]]
];
